import { type StatusType } from "@/components/shared/StatusBadge";

export interface BankMovement {
  id: string;
  date: string;
  description: string;
  reference?: string;
  amount: number;
  type: "debito" | "credito";
  suggestedAccount?: string;
  sncClass?: string;
  detectedEntity?: string;
  detectedEntityType?: "fornecedor" | "cliente";
  classificationStatus: StatusType;
  reconciliationStatus: StatusType;
  confidence: number;
  origin: "csv" | "sync" | "manual";
  linkedDocumentId?: string;
  linkedDocumentName?: string;
  aiExplanation?: string;
  isRecurring?: boolean;
  isDuplicate?: boolean;
  isAnomaly?: boolean;
}

export const mockMovements: BankMovement[] = [
  {
    id: "mv-1",
    date: "2024-03-08",
    description: "TRANSF P/ ABC MATERIAIS LDA",
    reference: "TRF-2024030801",
    amount: -2450.0,
    type: "debito",
    suggestedAccount: "62.1.1",
    sncClass: "62 — FSE",
    detectedEntity: "ABC Materiais, Lda.",
    detectedEntityType: "fornecedor",
    classificationStatus: "classificado",
    reconciliationStatus: "reconciliado",
    confidence: 96,
    origin: "csv",
    linkedDocumentId: "doc-1",
    linkedDocumentName: "fatura_abc_materiais_0847.pdf",
    aiExplanation: "Fornecedor recorrente com 14 transações anteriores. Todas classificadas como FSE — Subcontratos. Montante dentro do intervalo habitual (€1.800–€3.200).",
    isRecurring: true,
  },
  {
    id: "mv-2",
    date: "2024-03-07",
    description: "TRANSF DE SILVA E FILHOS SA",
    reference: "TRF-2024030701",
    amount: 5200.0,
    type: "credito",
    suggestedAccount: "72.1",
    sncClass: "72 — Prestações de Serviços",
    detectedEntity: "Silva & Filhos, S.A.",
    detectedEntityType: "cliente",
    classificationStatus: "classificado",
    reconciliationStatus: "reconciliado",
    confidence: 94,
    origin: "csv",
    linkedDocumentId: "doc-2",
    linkedDocumentName: "recibo_cliente_silva_rc0231.pdf",
    aiExplanation: "Cliente identificado pelo NIF na descrição. Valor corresponde à fatura #RC-0231.",
    isRecurring: true,
  },
  {
    id: "mv-3",
    date: "2024-03-07",
    description: "PAGAMENTO EDP COMERCIAL",
    reference: "DD-EDP-MAR24",
    amount: -890.0,
    type: "debito",
    suggestedAccount: "62.2.1",
    sncClass: "62 — FSE",
    detectedEntity: "EDP Comercial",
    detectedEntityType: "fornecedor",
    classificationStatus: "pendente",
    reconciliationStatus: "pendente",
    confidence: 72,
    origin: "csv",
    aiExplanation: "Fornecedor de utilities identificado. Montante 340% acima da média mensal (€202). Possível fatura de regularização ou erro.",
    isRecurring: true,
    isAnomaly: true,
  },
  {
    id: "mv-4",
    date: "2024-03-06",
    description: "TRANSF SEG SOCIAL MARCO",
    reference: "SS-MAR-2024",
    amount: -890.0,
    type: "debito",
    suggestedAccount: "24.5",
    sncClass: "24 — Estado e Outros Entes Públicos",
    detectedEntity: "Segurança Social",
    detectedEntityType: "fornecedor",
    classificationStatus: "revisto",
    reconciliationStatus: "reconciliado",
    confidence: 99,
    origin: "csv",
    aiExplanation: "Pagamento mensal recorrente à Segurança Social. Valor consistente com meses anteriores.",
    isRecurring: true,
  },
  {
    id: "mv-5",
    date: "2024-03-05",
    description: "DEPOSITO NUMERARIO",
    amount: 1000.0,
    type: "credito",
    classificationStatus: "pendente",
    reconciliationStatus: "pendente",
    confidence: 15,
    origin: "csv",
    aiExplanation: "Depósito em numerário sem referência identificável. Sem correspondência com faturas ou clientes conhecidos. Requer revisão manual.",
    isAnomaly: true,
  },
  {
    id: "mv-6",
    date: "2024-03-05",
    description: "COMISSAO MANUTENCAO CONTA",
    reference: "COM-MAR24",
    amount: -15.0,
    type: "debito",
    suggestedAccount: "68.1",
    sncClass: "68 — Outros Gastos e Perdas",
    detectedEntity: "Banco",
    detectedEntityType: "fornecedor",
    classificationStatus: "classificado",
    reconciliationStatus: "reconciliado",
    confidence: 98,
    origin: "csv",
    aiExplanation: "Comissão bancária mensal recorrente. Classificação automática aplicada.",
    isRecurring: true,
  },
  {
    id: "mv-7",
    date: "2024-03-04",
    description: "TRANSF P/ CONSULTORIA PRO SA",
    reference: "TRF-2024030401",
    amount: -3600.0,
    type: "debito",
    suggestedAccount: "62.2.2",
    sncClass: "62 — FSE",
    detectedEntity: "Consultoria Pro, S.A.",
    detectedEntityType: "fornecedor",
    classificationStatus: "extraído",
    reconciliationStatus: "pendente",
    confidence: 88,
    origin: "csv",
    linkedDocumentId: "doc-6",
    linkedDocumentName: "fatura_servicos_consultoria.pdf",
    aiExplanation: "Fornecedor identificado. Fatura correspondente localizada — valores coincidem.",
    isRecurring: false,
  },
  {
    id: "mv-8",
    date: "2024-03-03",
    description: "TRANSF P/ IMOBILIARIA CENTRAL",
    reference: "RENDA-MAR24",
    amount: -1200.0,
    type: "debito",
    suggestedAccount: "62.2.3",
    sncClass: "62 — FSE",
    detectedEntity: "Imobiliária Central",
    detectedEntityType: "fornecedor",
    classificationStatus: "classificado",
    reconciliationStatus: "pendente",
    confidence: 91,
    origin: "csv",
    linkedDocumentId: "doc-7",
    linkedDocumentName: "recibo_renda_escritorio.pdf",
    aiExplanation: "Renda mensal recorrente. Valor consistente. Documento correspondente identificado.",
    isRecurring: true,
  },
  {
    id: "mv-9",
    date: "2024-03-02",
    description: "TRANSF DE XYZ SERVICOS LDA",
    reference: "NC-2024-003",
    amount: 320.0,
    type: "credito",
    suggestedAccount: "62.1.1",
    sncClass: "62 — FSE (Nota de Crédito)",
    detectedEntity: "XYZ Serviços, Lda.",
    detectedEntityType: "fornecedor",
    classificationStatus: "extraído",
    reconciliationStatus: "pendente",
    confidence: 82,
    origin: "csv",
    linkedDocumentId: "doc-5",
    linkedDocumentName: "nota_credito_fornecedor_xyz.pdf",
    aiExplanation: "Crédito de fornecedor — corresponde a nota de crédito #NC-2024-003.",
  },
  {
    id: "mv-10",
    date: "2024-03-01",
    description: "TRANSF P/ IMOBILIARIA CENTRAL",
    reference: "RENDA-MAR24-DUP",
    amount: -1200.0,
    type: "debito",
    suggestedAccount: "62.2.3",
    sncClass: "62 — FSE",
    detectedEntity: "Imobiliária Central",
    detectedEntityType: "fornecedor",
    classificationStatus: "pendente",
    reconciliationStatus: "pendente",
    confidence: 45,
    origin: "csv",
    aiExplanation: "Possível duplicação — mesmo valor e fornecedor que mv-8 (01/Mar vs 03/Mar). Requer verificação.",
    isDuplicate: true,
    isAnomaly: true,
  },
];

export const classificationSummary = {
  total: mockMovements.length,
  autoClassified: mockMovements.filter((m) => m.classificationStatus === "classificado" || m.classificationStatus === "revisto").length,
  pendingReview: mockMovements.filter((m) => m.classificationStatus === "pendente" || m.classificationStatus === "extraído").length,
  anomalies: mockMovements.filter((m) => m.isAnomaly).length,
  duplicates: mockMovements.filter((m) => m.isDuplicate).length,
  recurring: mockMovements.filter((m) => m.isRecurring).length,
};
